### ISSUE TITLE
ValueError: 'CHI_TRIGONALBIPYRAMIDAL' is not in list

### ISSUE THREAD

**Issue by EchoShoot** [chao1224/MoleculeSDE#5]
3795548it [35:35, 2047.74it/s][17:51:48] WARNING: not removing hydrogen atom without neighbors
3803453it [35:40, 1777.16it/s]
Extracting 3D positions from SDF files for Training Data...
25308it [00:18, 1335.28it/s]
Traceback (most recent call last):
  File "generate_PCQM4Mv2.py", line 6, in <module>
    test_dataset = PCQM4Mv2(root=root_dir, transform=None)
  File "/data/temp/GTAM/modules/datasets/dataset_PCQM4Mv2.py", line 74, in __init__
    super(PCQM4Mv2, self).__init__(root, transform, pre_transform, pre_filter)
  File "/usr/local/anaconda3/envs/gRisk/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
  File "/usr/local/anaconda3/envs/gRisk/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 97, in __init__
    self._process()
  File "/usr/local/anaconda3/envs/gRisk/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 230, in _process
    self.process()
  File "/data/temp/GTAM/modules/datasets/dataset_PCQM4Mv2.py", line 137, in process
    data, _ = mol_to_graph_data_obj_simple_3D(mol)
  File "/data/temp/GTAM/modules/datasets/dataset_utils.py", line 121, in mol_to_graph_data_obj_simple_3D
    atom_feature = atom_to_feature_vector(atom)
  File "/usr/local/anaconda3/envs/gRisk/lib/python3.7/site-packages/ogb/utils/features.py", line 60, in atom_to_feature_vector
    allowable_features['possible_chirality_list'].index(str(atom.GetChiralTag())),
ValueError: 'CHI_TRIGONALBIPYRAMIDAL' is not in list

**Comment by chao1224** [comment]
Hi @EchoShoot , this should be the issue with OGB version.
Can you downgrade your OGB package? Like 1.2.1.

**Comment by EchoShoot** [comment]
It works！ thanks！
